//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_gasolineraEntities1 : DbContext
    {
        public db_gasolineraEntities1()
            : base("name=db_gasolineraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_proveedor> tbl_proveedor { get; set; }
        public virtual DbSet<tbl_abastece> tbl_abastece { get; set; }
        public virtual DbSet<tbl_asignado> tbl_asignado { get; set; }
        public virtual DbSet<tbl_bitacora> tbl_bitacora { get; set; }
        public virtual DbSet<tbl_bitacora_deta> tbl_bitacora_deta { get; set; }
        public virtual DbSet<tbl_bomba> tbl_bomba { get; set; }
        public virtual DbSet<tbl_cisterna> tbl_cisterna { get; set; }
        public virtual DbSet<tbl_empleado> tbl_empleado { get; set; }
        public virtual DbSet<tbl_empmail> tbl_empmail { get; set; }
        public virtual DbSet<tbl_emptel> tbl_emptel { get; set; }
        public virtual DbSet<tbl_estacion> tbl_estacion { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
        public virtual DbSet<tbl_realiza> tbl_realiza { get; set; }
        public virtual DbSet<tbl_telEst> tbl_telEst { get; set; }
        public virtual DbSet<tbl_venta> tbl_venta { get; set; }
    }
}
