//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_estacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_estacion()
        {
            this.tbl_asignado = new HashSet<tbl_asignado>();
            this.tbl_bomba = new HashSet<tbl_bomba>();
            this.tbl_cisterna = new HashSet<tbl_cisterna>();
            this.tbl_telEst = new HashSet<tbl_telEst>();
        }
    
        public int est_codigo { get; set; }
        public string est_nombre { get; set; }
        public string est_Registro { get; set; }
        public System.DateTime est_InOperacion { get; set; }
        public string est_direccion { get; set; }
        public string est_dpto { get; set; }
        public string est_ciudad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_asignado> tbl_asignado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bomba> tbl_bomba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cisterna> tbl_cisterna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_telEst> tbl_telEst { get; set; }
    }
}
