//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bitacora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_bitacora()
        {
            this.tbl_bitacora_deta = new HashSet<tbl_bitacora_deta>();
        }
    
        public int bi_id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string usuario { get; set; }
        public string nombrePC { get; set; }
        public string objeto { get; set; }
        public string accion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bitacora_deta> tbl_bitacora_deta { get; set; }
    }
}
