//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cisterna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cisterna()
        {
            this.tbl_abastece = new HashSet<tbl_abastece>();
        }
    
        public string cst_capacidad { get; set; }
        public string cst_diametro { get; set; }
        public string cst_altura { get; set; }
        public string cst_tipo { get; set; }
        public System.DateTime cst_UltimaFech { get; set; }
        public string cst_CapActual { get; set; }
        public int est_codigo { get; set; }
        public int cst_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_abastece> tbl_abastece { get; set; }
        public virtual tbl_estacion tbl_estacion { get; set; }
    }
}
