//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_abastece
    {
        public int est_codigo { get; set; }
        public int cst_codigo { get; set; }
        public int prv_codigo { get; set; }
        public System.DateTime ab_fecha { get; set; }
        public int ab_cantidadABS { get; set; }
        public decimal ab_montoABS { get; set; }
    
        public virtual tbl_proveedor tbl_proveedor { get; set; }
        public virtual tbl_cisterna tbl_cisterna { get; set; }
    }
}
