//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_empleado()
        {
            this.tbl_asignado = new HashSet<tbl_asignado>();
            this.tbl_empmail = new HashSet<tbl_empmail>();
            this.tbl_emptel = new HashSet<tbl_emptel>();
        }
    
        public int emp_codigo { get; set; }
        public string emp_nombre { get; set; }
        public string emp_ID { get; set; }
        public string emp_seguro { get; set; }
        public System.DateTime emp_fecIngre { get; set; }
        public System.DateTime emp_fechEgre { get; set; }
        public System.DateTime emp_fechNac { get; set; }
        public int emp_edad { get; set; }
        public string emp_salida { get; set; }
        public string emp_puesto { get; set; }
        public decimal emp_salarioN { get; set; }
        public string emp_Tcontrato { get; set; }
        public string emp_direccion { get; set; }
        public string emp_genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_asignado> tbl_asignado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_empmail> tbl_empmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emptel> tbl_emptel { get; set; }
    }
}
