//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_venta
    {
        public int bmb_codigo { get; set; }
        public System.TimeSpan vnt_hora { get; set; }
        public decimal vnt_montoV { get; set; }
        public System.DateTime vnt_FechVent { get; set; }
        public string vnt_TotVentaLit { get; set; }
    
        public virtual tbl_bomba tbl_bomba { get; set; }
        public virtual tbl_realiza tbl_realiza { get; set; }
    }
}
