//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empmail
    {
        public int emp_codigo { get; set; }
        public string eem_email { get; set; }
    
        public virtual tbl_empleado tbl_empleado { get; set; }
    }
}
