//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gasolinera.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bitacora_deta
    {
        public int bi_id { get; set; }
        public int bi_num { get; set; }
        public string campo { get; set; }
        public string valor { get; set; }
    
        public virtual tbl_bitacora tbl_bitacora { get; set; }
    }
}
